### ISSUE TITLE
Hangs on buffering

### ISSUE THREAD

**Issue by djnice** [TorrentStream/TorrentStream-Android#56]
Hello,
Torrent files from itorrent.ws are not working. The progress bar hangs on random position, never goes up to 100%.

Please check.

**Comment by se-bastiaan** [comment]
I cannot help you without any information. What have you tried so far? Did you check if the behaviour matches #49?

**Comment by djnice** [comment]
I don't see any error in the log, I used your sample code, only changed the torrent link.
I tried with emulator, on my phone and with Fire TV 4K, but same behavior, the progressbar is stopped after a time.

**Comment by se-bastiaan** [comment]
You should be able to add some logging to the sample to find out what is happening exactly.
Maybe try https://github.com/masterwok/simple-torrent-android to see if it works for you.

**Comment by mvorisis** [comment]
I have the same problem, it just stops at random progress, I tried these urls:
https://yts.mx/torrent/download/742D4DE6242D8A8553384A4F835ABE5CC7A6B0A2
magnet:?xt=urn:btih:742D4DE6242D8A8553384A4F835ABE5CC7A6B0A2&dn=21+Bridges+%282019%29+%5B720p%5D+%5BYTS.LT%5D&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337

I tried these urls with the [https://github.com/TorrentStream/TorrentStream-Android](torrent-stream) repo and they are playing fine.

If you have time please check it because I too don't see any errors
