### ISSUE TITLE
totrent streaming stops and further no video is streaming occurs

### ISSUE THREAD

**Issue by akshayachu09** [TorrentStream/TorrentStream-Android#64]

**Comment by akshayachu09** [comment]
@se-bastiaan sir i need help i builded your application it works. but after streaming video it stops and further no streaminh will occur.
and the file will found in the file manager without remove if i exit the app too
please hlep

**Comment by akshayachu09** [comment]
@se-bastiaan  i am using android phonebfor editing.aide is the application

**Comment by se-bastiaan** [comment]
You need to create a description for your issue. It is unclear what your issue is and what you have tried to solve it.

**Comment by akshayachu09** [comment]
@se-bastiaan 
sir this app streams and stops after few minutes stream.and no further playingbof video occurs

**Comment by akshayachu09** [comment]
@se-bastiaan will you give your whatsapp number please

**Comment by se-bastiaan** [comment]
No I will not. This repository and it's issue tracker exists for questions and problem solving. But just with 'it streams and then stops' I cannot help you. You are not sharing any logcat outputs or anything that can help me suggest you what to do next.

This is not a help desk, the code in this repository is distributed as is. If you have any problems I do expect you to express the problems you are encountering in detail so that I may be able to help. With the current information you are providing I can only keep asking for more, which you apparently do not want or can give. So unfortunately that means I cannot help you.
