### ISSUE TITLE
Need help regarding setInterestedBytes

### ISSUE THREAD

**Issue by Vasu7052** [TorrentStream/TorrentStream-Android#75]
Can't see any examples/documentation on how to calculate bytes as a parameter for setInterestedBytes. My use case is to seek video to anywhere in the middle. I don't want to use Android TorrentStreamServer Library. And also where to perform setInterestedBytes, i.e. in onStreamPrepared or onStreamStarted or onStreamReady?

Note: I'm using MX Player as an external video player

**Comment by se-bastiaan** [comment]
Hi.

None of those places would work. You need to decide what bytes you want at the moment where you are seeking.

**Comment by Vasu7052** [comment]
thanks for the quick response. so how can i calculate the bytes for the position that i want to seek?

**Comment by se-bastiaan** [comment]
That depends on the video and format, so your video player will probably determine this.

That's what the server tool is for, since you're using an external video player you have no way of knowing unless you create your own way of streaming the file. The video player doesn't know that it is reading an incomplete file.
